/*
	SPI - Serial Peripheral Interface

	-Four Wire Serial Interface
	-Speed Improvement over UART/I2C
	-Supports full-duplex communication

	-Very loosely "define"
		- That it does not specify frame formats,no.of bits transmitted, even voltage levels

	-SPI Is more often used for transferring data between a "smart" controller and a "less smart" peripheral device

	-MOSI: Master out Slave in used to send data from master to slave
	-MISO: Master in slave out Master in slave out Use to send data from slave device to master
	-SCK:  Serial clock Used to generate clock to synchronise data transfer between the master and slave device .Generated by the master
	-SS:   Slave select Used to select a particular slave in the spi multiple slaves configuration

	Clock Phase and polarity
		-Master and slave device must agree on clock phase and polarity
		-CPOL: Clock Polarity
		-CPHA: Clock Phase
		-Combinations of CPOL and CPHA are referred to as SPI bus modes.

	NSS Management:
		NSS Software mode:
			SS line is driven internally by the firmware
		NSS Hardware mode:
			A dedicated GPIO pin is used to drivee the SS Line
			-NSS Output Enabled:
				used only when device operates in master mode.
			-NSS Output Disabled:
				Allows multi-master capability for devices operating in master mode

*/
#include "SPI.h"

uint8_t tx_data[] = {0xAA, 0xBB, 0xCC};
uint8_t rx_data_spi1[3];
uint8_t rx_data_spi2[3];

int main(void)
{
	// Initialize GPIOs for SPI1 and SPI2
	spi_gpio_init();      // PA5,6,7 + PA9 for CS
	spi2_gpio_init();     // PB13,14,15

	// Configure SPI1 as master and SPI2 as slave
	spi_config();         // SPI1 master
	spi2_config();        // SPI2 slave

	cs_enable();          // Pull CS low to select slave

	for (int i = 0; i < 3; i++)
	{
		// Wait until SPI1 TXE is set
		while (!(SPI1->SR & SR_TXE)) {}

		// Write data to SPI1
		SPI1->DR = tx_data[i];

		// Wait until SPI2 RXNE is set
		while (!(SPI2->SR & SR_RXNE)) {}

		// Read received data from SPI2
		rx_data_spi2[i] = SPI2->DR;

		// Wait until SPI1 RXNE is set (to read dummy MISO)
		while (!(SPI1->SR & SR_RXNE)) {}

		// Read received data from SPI1 (optional)
		rx_data_spi1[i] = SPI1->DR;
	}

	// Wait until SPI1 is not busy
	while (SPI1->SR & SR_BSY) {}

	cs_disable();         // Pull CS high to deselect slave

	while (1)
	{
		// You can toggle an LED or send rx_data_spi2[] over UART for verification
	}
}
